apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: thesis-defense-agent
  labels:
    app.kubernetes.io/name: thesis-defense-agent-prometheus
    app.kubernetes.io/part-of: thesis-defense-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: thesis-defense-agent-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
